apiVersion: v1
kind: Pod
metadata:
  name: mypod-testing1
spec:
  nodeName: node2
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: vol2
  volumes:
    - name: vol2
      persistentVolumeClaim:
        claimName: claim1

