apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume1
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /volume1
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kamal
            operator: In
            values:
            - ji

