apiVersion: v1
kind: Pod
metadata: 
  name: high-priority
spec:
  containers:
  - name: high-priority
    image: mysql
    command: ["/bin/sh"]
    args: ["-c", " while true; do echo hello; sleep 10; done"]
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1
